version: 1
sources:
  - type: gdrive
    configured: true
    lastSync: 2026-01-22T12:07:36.588Z
  - type: linear
    configured: true
    lastSync: 2026-01-22T14:37:46.900Z
  - type: hubspot
    configured: true
    lastSync: 2026-01-28T09:39:38.494Z
